### ISSUE TITLE
pass multiples params to spawn

### ISSUE THREAD

**Issue by rafaoli** [olle/electron-starter#1]
Hi, I liked, for example.
I'm not able to add the -Dserver.port = 8081 parameter to run on a specific port, because it might be dynamic.
I have tried the following:

var args = [
        '-jar', __dirname + '/target/sqlite-db-sample-0.1.0.jar',
        '-Dserver.port=', '8081'      
      ];

      var child = spawn('java', args,  {
        detached: true,
        stdio: ['ignore', out, err]
      });
      child.unref();

**Comment by olle** [comment]
Hi, sorry for not answering in an eternity.

I got it to work by passing the port params first, and ensuring that `'-jar', __dirname + '/target/sqlite-db-sample-0.1.0.jar'` came last. Like this:

```
var child = spawn(
    "java",
    ["-Dserver.port=8181", "-jar", __dirname + "/target/app.jar"],
    {
      detached: true,
      stdio: ["ignore", out, err],
    }
  );
  ```

Hope this helps. Cheers!
